# [START cloudbuild_gradle]
steps:
  - name: gradle:7.4.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:7.4.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$env.PROJECT_ID/$env.SERVICE_NAME::$GITHUB_SHA", "--build-arg=JAR_FILE=build/libs/name-svc-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$env.PROJECT_ID/$env.SERVICE_NAME:$GITHUB_SHA"]
# [END cloudbuild_gradle]