# [START cloudbuild_gradle]
steps:

  # Test the build
  - name: gradle:7.4.2-jdk8
    entrypoint: gradle
    args: ["test"]

 # Assemble the jar
  - name: gradle:7.4.2-jdk8
    entrypoint: gradle
    args: ["assemble"]

  # Build the image
  - name: gcr.io/cloud-builders/docker
    args: [
        "build",
        "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_COMMIT_SHA",
        "--build-arg=JAR_FILE=build/libs/name-svc.jar",
        "."]

  # Push the container image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_COMMIT_SHA']

images: ["gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_COMMIT_SHA"]
# [END cloudbuild_gradle]