spring.cloud.gcp.project-id: team-ipg-wf

# port will be assigned on GCP, default to 8080 local
server.port: ${PORT:8080}

# Allow larger file limits for uploading
spring.servlet.multipart.max-file-size: 128MB
spring.servlet.multipart.max-request-size: 128MB