name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: my-service

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'test'
        uses: gradle:7.4.2-jdk11
        entrypoint: gradle
        args: ["test"]

      - name: build
        uses: gradle:7.4.2-jdk11
        entrypoint: gradle
        args: ["package"]

      - name: 'build-image'
        uses: gcr.io/cloud-builders/docker
        args: ["build", "-t", "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA", "--build-arg=JAR_FILE=build/libs/name-svc-0.0.1-SNAPSHOT.jar", "."]
        images: ["gcr.io/$PROJECT_ID/$SERVICE_NAME"]

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
          service: '${{ env.SERVICE_NAME }}'
          region: '${{ env.RUN_REGION }}'
          env_vars: 'NAME="test"'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
