name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: my-service

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --config /cloudbuild.yaml \
            /

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
          service: '${{ env.SERVICE_NAME }}'
          region: '${{ env.RUN_REGION }}'
          env_vars: 'NAME="test"'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
